services:
  webapp:
    image: jai-workspace
    volumes:
      - $JAI_HOME:/jai:ro
      - .:/workspace:rw
    working_dir: /workspace
    ports:
      - "7000:7000"
    restart: on-failure
    tty: true
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
