services:
  workspace:
    image: jai-workspace
    volumes:
      - $JAI_HOME:/jai:ro
      - .:/workspace:rw
    working_dir: /workspace
    command: bash ./server.sh
    expose:
      - "7000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "7000:80"
