services:
  workspace:
    image: jai-workspace
    volumes:
      - $JAI_HOME:/jai:ro
      - .:/workspace:rw
      - /Users/kevin/kfinn/jai-postgres:/vendor/jai-postgres:rw
    working_dir: /workspace
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
